#!/bin/bash

# (Quick and dirty)
#
# Uses racadm to clear iDRAC job queue.

me=$(basename $0)

machines="$@"

if [[ -z "$machines" ]]; then
   >&2 echo "Syntax: $me <machine_name> [<machine_name> ...]"
   exit 5
fi

for machine_name in $machines; do
   echo "Cleairng job queue on $machine_name."
   run-racadm $machine_name jobqueue delete -i JID_CLEARALL_FORCE
done


