#!/bin/bash

# Emits MachineConfig manifests that configures NTP time sync.

function make_encoded_config {

cat << E-O-D | base64 -w0
pool 2.rhel.pool.ntp.org iburst
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
keyfile /etc/chrony.keys
leapsectz right/UTC
keyfile /etc/chrony.keys
logdir /var/log/chrony
E-O-D
}

entry_number=1

function emit_mc_manifest {

if [[ $entry_number -gt 1 ]]; then
   echo "---"
fi

local role="$1"
local encoded_file="$2"

cat << E-O-D
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: $role
  name: 999-$role-etc-chrony-conf
  namespace: openshift-machine-config-operator
spec:
  config:
    ignition:
      version: 3.1.0
    passwd: {}
    storage:
      files:
      - filesystem: root
        path: /etc/chrony.conf
        overwrite: true
        mode: 0755
        user:
          name: root
        group:
          name: root
        contents:
          source: data:text/plain;charset=utf-8;base64,$encoded_file
  fips: false
  kernelArguments: null
  kernelType: ""
  osImageURL: ""
E-O-D

entry_number=$((entry_number+1))
}

encoded_config=$(make_encoded_config)
emit_mc_manifest "master" "$encoded_config"

exit 0

