#!/bin/bash

# Emits entries to put into dhcpd.conf to configure fixed IPs for specified
# bare metal machines, using data in the "database" yaml.

my_dir=$(dirname $(readlink -f $0))
machine_names="$@"


function extract {
   echo "$1" | jq -rc "$2"
}

function extract_raw {
   echo "$1" | jq -r "$2"
}

function emit_dhcpd_entry {

cat << E-O-D
  host $machine_name-nic2 { hardware ethernet $dhcpd_mac_address; fixed-address $dhcpd_fixed_ip; }
E-O-D
}

first_one=1
entry_number=0
for machine_name in $machine_names; do
   entry_number=$((entry_number+1))

   # Grab the machine's entry from the "database".
   m_data=$($my_dir/get-machine-entry $machine_name)

   # Get/form subsitution data for dhcpd entry emitted via function above.

   # Get MAC address for NIC 2 since that's the one connectd to the
   # slot's private data network.

   dhcpd_mac_address=$(extract "$m_data" ".nics.nic2.mac_address")

   # Get the fixed IP addresses we've assigned to NIC 2 on the data
   # network for Slot 0.  That will be be thing we put into the
   # dhcpd template, for later customization based on actual slot.

   dhcpd_fixed_ip=$(extract  "$m_data" ".cluster_internal_networking.nic2.dhcp_ip_address")

  emit_dhcpd_entry

done

exit 0

