#!/bin/python3

# Author: J. M. Gdaniec, Jan 2021

from bmc_common import *

import json
import os
import sys
import traceback
import yaml

# Main:

try:

   machine_name = "fog01"

   # Get BMC address and creds from our machine info database (yaml file).

   machine_db_yaml = os.getenv("FOG_MACHINE_INFO")
   if machine_db_yaml is None:
      die("Environment variable FOG_MACHINE_INFO is not set.")

   # Load DB and convert it into a dict indexed by machine name.
   try:
      with open(machine_db_yaml, "r") as stream:
         machine_db = yaml.safe_load(stream)
   except FileNotFoundError:
      die("Machine info database file not found: %s" % machine_db_yaml)

   try:
      machine_info = {e["name"]: e for e in machine_db["machines"]}
   except KeyError:
      die("Machine info db not as expected (no machines list).")

   m_entry = None
   try:
      m_entry = machine_info[machine_name]
      bmc_info = m_entry["bmc"]
      bmc_address = bmc_info["address"]
      bmc_username = bmc_info["username"]
      bmc_password = bmc_info["password"]
      redfish_stuff = bmc_info["redfish"]
   except KeyError:
      if m_entry is None:
         die("Machine %s not recored in machine info db." % machine_name)
      else:
         die("Machine info db not as expected (bmc data missing/wrong).")


except Exception:
   traceback.print_exc()
   die("Unhandled exception!")



