#!/bin/bash

me=$(basename "$0")

# Provides machine config data for a specified machine.

my_dir=$(dirname $(readlink -f $0))
default_data_yaml="$my_dir/../fog-machine-info/fog-info.yaml"

# Try current env var names first
data_yaml="${ACM_LAB_MACHINE_INFO}"
creds_yaml="${ACM_LAB_MACHINE_CREDS}"

# And then deprecated ones for caompaibility
data_yaml="${data_yaml:-$FOG_MACHINE_INFO}"
creds_yaml="${creds_yaml:-$FOG_MACHINE_CREDS}"

# And then fall back to default
data_yaml="${data_yaml:-$default_data_yaml}"

# Complain if something is missing.
if [[ ! -f "$data_yaml" ]]; then
   >&2 echo "Error: Can not find machine-info yaml file."
   exit 5
fi
if [[ ! -f "$creds_yaml" ]]; then
   >&2 echo "Error: Can not find machine-creds yaml file."
   exit 5
fi

tmp_file=$(mktemp -t "$me.XXXXXXXX")

machine_name="$1"
yq -c ".machines | .[] | select(.name==\"$machine_name\")" $data_yaml > $tmp_file

bmc_username=$(jq -r ".bmc.username" $tmp_file)
bmc_password=$(jq -r ".bmc.password" $tmp_file)

if [[ "$bmc_username" != "null" ]] & [[ "$bmc_password" != "null" ]]; then
   cat "$tmp_file"
   rm -f "$tmp_file"
   exit
fi

# Maybe later we'll allow per-machine creds entries and prefer them to
# global ones, but for now we just support global ones.

bmc_username=$(yq -r ".global.bmc.username" "$creds_yaml")
bmc_password=$(yq -r ".global.bmc.password" "$creds_yaml")

jq -c ".bmc += {\"username\": \"$bmc_username\", \"password\": \"$bmc_password\"}" $tmp_file

rm -f "$tmp_file"
