#!/bin/python3

# Displays the BMC's System resource representing the Server it manages.

# Author: J. M. Gdaniec, Apr 2021

from lab_common import *

import argparse
import traceback

def main():

   # set_dbg_volume_level(5)

   parser = argparse.ArgumentParser()
   parser.add_argument("machine" )
   LabBMCConnection.add_bmc_login_argument_definitions(parser)

   args = parser.parse_args()

   machine   = args.machine

   bmc_conn = LabBMCConnection.create_connection(machine, args)

   res = bmc_conn.get_system_resource()
   print(json_dumps(res))

if __name__ == "__main__":
   try:
      main()
   except BMCRequestError as exc:
      die(str(exc))
   except Exception:
      traceback.print_exc()
      die("Unhandled exception!")

