#!/bin/bash

# Provides machine config data for a specified machine.

my_dir=$(dirname $(readlink -f $0))
default_data_yaml="$my_dir/../fog-machine-data/fog-data.yaml"
default_creds_yaml="$my_dir/fog-machine-creds.yaml"

data_yaml="${FOG_MACHINE_INFO:-$default_data_yaml}"
creds_yaml="${FOG_MACHINE_CREDS:-$default_creds_yaml}"

tmp_file="./.tmp.json"

machine_name="$1"
yq -c ".machines | .[] | select(.name==\"$machine_name\")" $data_yaml > $tmp_file

bmc_username=$(jq -r ".bmc.username" $tmp_file)
bmc_password=$(jq -r ".bmc.password" $tmp_file)

if [[ "$bmc_username" != "null" ]] & [[ "$bmc_password" != "null" ]]; then
   cat "$tmp_file"
   rm -f "$tmp_file"
   exit
fi

# Maybe later we'll allow per-machine creds entries and prefer them to
# global ones, but for now we just support global ones.

bmc_username=$(yq -r ".global.bmc.username" "$creds_yaml")
bmc_password=$(yq -r ".global.bmc.password" "$creds_yaml")

jq -c ".bmc += {\"username\": \"$bmc_username\", \"password\": \"$bmc_password\"}" $tmp_file

rm -f "$tmp_file"
