#!/bin/bash

# (Quick and dirty)
#
# Runs racadm targetting a lab machine specified by the short machine name.
#
# Uses the ACM Lab creds obtained from the "bmc" entry.
#
# Requires:
# - racadm
# - jq

me=$(basename $0)

machine_name=$1
shift 1

if [[ -z "$machine_name" ]] || [[ -z "$1" ]]; then
   >&2 echo "Syntax: $me <machine_name> <racadm_cmd>"
   exit 5
fi

bmc_addr=$(get-machine-entry "$machine_name" | jq -r .bmc.address)
bmc_username=$(get-acm-lab-creds -u "bmc")
bmc_password=$(get-acm-lab-creds -p "bmc")

sudo racadm -r "$bmc_addr" -u "$bmc_username" -p "$bmc_password" "$@"
