
# This install-config.yaml is an exampleof a config for a slot numbered
# <slot_nr> as set up by ACM bare-metal slot setup tools.
#
# Replace <slot_nr> with the actual slot number, and also replace the example
# platform.baremetal.host entries with ones containing the actual addresses,
# MAC addresses, userid/password etc. for each machine.

apiVersion: v1
baseDomain: my-base-domain.red-chesterfield.com
metadata:
  name: my-cluster-name

networking:
  machineCIDR: 172.31.<slot_nr>.0/24
  networkType: OVNKubernetes

compute:
- name: worker
  replicas: 1
  platform:
    baremetal: {}
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}

platform:
  baremetal:
    libvirtURI: qemu+ssh://provisioner@172.22.<slot_nr>.1/system
    apiVIP: 172.31.<slot_nr>.10
    ingressVIP: 172.31.<slot_nr>.11
    provisioningNetworkInterface: eno1
    provisioningDHCPExternal: false
    provisioningNetworkCIDR: 172.22.<slot_nr>.0/24
    provisioningDHCPRange: 172.22.<slot_nr>.200,172.22.<slot_nr>.249
    bootstrapProvisioningIP: 172.22.<slot_nr>.5
    clusterProvisioningIP: 172.22.<slot_nr>.6
    provisioningHostIP: 172.22.<slot_nr>.6
    externalBridge: data
    provisioningBridge: provisioning

    hosts:
    - name: fog07.cluster.internal
      role: master
      bmc:
        address: redfish://fog07.mgmt.acm-lab.redhat.com/redfish/v1/Systems/System.Embedded.1
        disableCertificateVerification: true
        username: "<BMC-Username>"
        password: "<BMC-Passrod>"
      bootMACAddress: ab:cd:ef:01:23:07
      hardwareProfile: default 
      rootDeviceHints:
        deviceName: /dev/sda

    - name: fog08.cluster.internal
      role: master
      bmc:
        address: redfish://fog08.mgmt.acm-lab.redhat.com/redfish/v1/Systems/System.Embedded.1
        disableCertificateVerification: true
        username: "<BMC-Username>"
        password: "<BMC-Passrod>"
      bootMACAddress: ab:cd:ef:01:23:08
      hardwareProfile: default 
      rootDeviceHints:
        deviceName: /dev/sda

    - name: fog09.cluster.internal
      role: master
      bmc:
        address: redfish://fog09.mgmt.acm-lab.redhat.com/redfish/v1/Systems/System.Embedded.1
        disableCertificateVerification: true
        username: "<BMC-Username>"
        password: "<BMC-Passrod>"
      bootMACAddress: ab:cd:ef:01:23:09
      hardwareProfile: default 
      rootDeviceHints:
        deviceName: /dev/sda

    - name: fog10.cluster.internal
      role: worker
      bmc:
        address: redfish://fog19.mgmt.acm-lab.redhat.com/redfish/v1/Systems/System.Embedded.1
        disableCertificateVerification: true
        username: "<BMC-Username>"
        password: "<BMC-Passrod>"
      bootMACAddress: ab:cd:ef:01:23:10
      hardwareProfile: unknown 
      rootDeviceHints:
        deviceName: /dev/sda

pullSecret: 'put your pull secret here'

# The following SSH key is the public part of the ACM Test Env key.  Please use it as is to
# allow common access to OCP nodes running in the bare metal lab to facilitate debugging when
# needed. Contact lab admins to get the private part of this key.

sshKey: |
   ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5e9lBM2s5ek5JZUOYgFHnfD6XFpvBLkHnVC+vt1LFGBfY9xAABXh4g64dsE0bN8KFXc43zjUXiFKtArI1l8SivA32m6d6nqz9FMKmsVcREWLKYIYR8RFS5aTHfdhmTYG0gjy66z98T0Tam0In5nc81nVxYNnzcW4FwqiwXi2vhuMZk3OZLf5u28PF/BJYxEnPFcrc4OhibDKJfwjkwvU7YiXaF4eS5N3NK9GtXGddOO84EQCXk8ieif72JgmdwhPeCK6a8PgV2iCJF9YiTJYuG1gg/Os5U+nlKervZBBq54MF1wzXYX3WXKx9j0//8cw+EJZuGZifqx8n6wcIRqA4ONMDs+rw5qPC8gnamhZeuAbTsfhtyRGchYUAxaDeJhs9V9rPTpGt0wD4KzCzeheWWYmO90DepDTClwkPEZpex6g2Io6RP+zamuGI2iDpWfg7kMtoEk7EoXACJQHkhtmSGn/sENnjJQWyKsYtA5nV9gTxhf29PxxGLusGNbDOdLomVwsiGHJkajG2cqFXRSW+WLQbIpMcZjJZ6XFS0qoIzQYoKP2PiAuq0JElh/EaOrMkJ5IT8hZFsy3F46FxR2ShX4ICXef6LZTnCMTpup8VbG4hnlT26x5746BbfRcqw5A56Mwj+F4Wy4od6iFRhREYLU72qHPbPy2QPCLnTBnN1w== ACM Test Env Key
