# Template of an install-config.yaml for bare metal install in ACM Eng Lab.
#
# <slot-nr>:
#   Number (1-n) of the slot holding the cluster.  This appears in IP addresses
#   of things on the slot's private provisioning and data networks as as to
#   keep the addressing of each slot distinct.  This will permit us to have
#   eg. a single hub with two or more bare-metal spoke clusters.
#
# <GAP_VM_IP>
#    IP address of the slot's "GAP" VM running on VSphere that acts as the host
#    of the OCP bootstrap node during provisioning, and as a network gateway for
#    access to the slot's private network.  GAP = "Gateway and Provisioner".
#
# Addressing conventions:
#
# - Slot-specific priavte provisioning network: 172.22.<slot-nr>.0/24
#
# - Slot-specific private data network: 172.31.<slot-nr>.0/24
#
# - GAP VM is on 172.22.<slot-nr>.1 and 172.31.<slot-nr>.1
#
# - The .2 and .3 addresses of these networks are reserved for other gateways.
#
# - Alternatie (eg. bare-metal-hosted) provisoining host is on 172.22.<slot-nr>.4
#   if sone of these is being used.
#
# - THe OCP boostrap machine is at 172.22.<slot-nr>.5 as specified in this
#   install-config.yaml, and probably on 172.31.<slot-nr>.5 as well due to fixed
#   DHCP config for the data network (in GAP VM).
#
# - Once installed, the OCP cluster will use address 172.31.<slot-nr>.6 for the 
#   provisioning machinery when running in-cluster.
#
# - The OCP bootstrap VM, and in-cluster provisioning machinery, provide DHCP for
#   the machines on the provisioning network with the address pool running from
#   172.22.<slot-nr>.200 to .249.
#
# - The GAP VM provides DHCP on the private datat network.
#
# - The OCP cluster's API and Ingress vips are 172.31.<slot-nr>.10 and .11 as
#   specified in this install-config.yaml.  Note that these addresses are hard
#   coded into the GAP setup scripts (for port fowarding) so if you want to use
#   other addreses, the firewall port forwarding will have to be changed as well.

apiVersion: v1
baseDomain: dev99.red-chesterfield.com
metadata:
  name: my-bare-metal-cluster

networking:
  machineCIDR: 172.31.<slot-nr>.0/24
  networkType: OVNKubernetes

compute:
- name: worker
  replicas: 3
  platform:
    baremetal: {}
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}

platform:
  baremetal:
    apiVIP: 172.31.<slot-nr>.10
    ingressVIP: 172.31.<slot-nr>.11
    provisioningNetworkInterface: eno1
    provisioningDHCPExternal: false
    libvirtURI: qemu+ssh://provisioner@<GAP-VM-IP>/system
    externalBridge: data
    provisioningBridge: provisioning
    provisioningNetworkCIDR: 172.22.<slot-nr>.0/24
    bootstrapProvisioningIP: 172.22.<slot-nr>.5
    clusterProvisioningIP: 172.22.<slot-nr>.6
    provisioningHostIP: 172.22.<slot-nr>.6
    provisioningDHCPRange: 172.22.<slot-nr>.200,172.22.<slot-nr>.249

    hosts:
      <List of Host entries as generated from Fog Machine Info>

pullSecret: '<your-pull-secret>'
sshKey: |
   <your-private-ssh-key>

